<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC201701031452" tests="4" failures="4" timestamp="11 Jan 2017 07:16:41 GMT" time="30.896" errors="0">
  <testcase name="loginFail" time="5.635" classname="LoginTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
	at org.webdriver.patatiumwebui.utils.Assertion.VerityError(Assertion.java:1041)
	at LoginTest.loginFail(LoginTest.java:59)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginFail -->
  <testcase name="loginFail" time="3.624" classname="LoginTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
	at org.webdriver.patatiumwebui.utils.Assertion.VerityError(Assertion.java:1041)
	at LoginTest.loginFail(LoginTest.java:59)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginFail -->
  <testcase name="loginFail" time="3.59" classname="LoginTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
	at org.webdriver.patatiumwebui.utils.Assertion.VerityError(Assertion.java:1041)
	at LoginTest.loginFail(LoginTest.java:59)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginFail -->
  <testcase name="loginFail" time="3.406" classname="LoginTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
	at org.webdriver.patatiumwebui.utils.Assertion.VerityError(Assertion.java:1041)
	at LoginTest.loginFail(LoginTest.java:59)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginFail -->
</testsuite>
